name = "vixter-media-worker"
main = "media-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "vixter-media-worker"

[env.staging]
name = "vixter-media-worker-staging"

# R2 bucket binding
[[r2_buckets]]
binding = "VIXTER_MEDIA"
bucket_name = "vixter-production"

# Environment variables
[vars]
R2_ACCOUNT_ID = "569b3a4a5f566a22d9db7146c13c9d69"
R2_BUCKET_NAME = "vixter-production"

# Secrets (set these via wrangler secret put)
# wrangler secret put NEXTAUTH_SECRET
# wrangler secret put R2_ACCESS_KEY_ID
# wrangler secret put R2_SECRET_ACCESS_KEY
